spring: 
   config:
      activate:
         on-profile: dev
         
   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: 
                  client-secret: 
                  scope: profile, email
                  redirect-uri: http://localhost:8080/oauth2/callback/google
                  client-name: google                           
               naver:
                  client-id: 
                  client-secret: 
                  redirect-uri: http://localhost:8080/oauth2/callback/naver
                  authorization-grant-type: authorization_code
                  client-name: naver
            provider:
               naver:
                  authorization-uri: https://nid.naver.com/oauth2.0/authorize
                  token-uri: https://nid.naver.com/oauth2.0/token
                  user-info-uri: https://openapi.naver.com/v1/nid/me
                  user-name-attribute: response  
                  
logging:
  config: classpath:log4j2.xml
                  
                      
my-props:    
   name:
      age: 100

---

spring: 
   config:
      activate:
         on-profile: prod 
         
         
   security:
      oauth2:
         client:
            registration:
               google:
                  client-id: 
                  client-secret: 
                  scope: profile
                  redirect-uri: http://www.foo.com/oauth2/callback/google
                  client-name: google                           
               naver:
                  client-id: 
                  client-secret:  
                  redirect-uri: http://www.foo.com/oauth2/callback/naver
                  authorization-grant-type: authorization_code
                  client-name: naver
            provider:
               naver:
                  authorization-uri: https://nid.naver.com/oauth2.0/authorize
                  token-uri: https://nid.naver.com/oauth2.0/token
                  user-info-uri: https://openapi.naver.com/v1/nid/me
                  user-name-attribute: response              

my-props:    
   name:
      age: 200
